
language: python

python:
  - "3.6"
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$(pwd)

before_install:
  - cd agent

install:
  - pip install -r requirements.txt

script:
  - py.test --verbose --cov-config .coveragerc --cov=sn_agent tests

after_success:
  - coveralls
