sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t singularitynet_agent agent

script:
  - docker run singularitynet_agent /bin/sh -c "./agent.sh test"

after_success:
  - docker run singularitynet_agent /bin/bash -c "coveralls"
