sudo: required

services:
  - docker

before_install:
  - docker build -t singularitynet_agent agent

script:
  - docker run --env-file travis_env singularitynet_agent /bin/sh -c "export PYTHONPATH=$PYTHONPATH:/code/;./agent.sh test"

after_success:
  - docker run singularitynet_agent /bin/bash -c "coveralls"
