sudo: required

services:
  - docker

env:
  global:
    - SN_AGENT_ID=b545478a-971a-48ec-bc56-4b9b7176799c
    - SN_SERVICE_ADAPTER_CONFIG_FILE=agent/service_adapter_config_example.yml

before_install:
  - docker build -t singularitynet_agent agent

script:
  - docker run singularitynet_agent /bin/sh -c "py.test --verbose --cov-config agent/.coveragerc --cov=sn_agent agent/tests"

after_success:
  - docker run singularitynet_agent /bin/bash -c "coveralls"
