
agent:
  build: agent
  environment:
    - SN_AGENT_ID=b545478a-971a-48ec-bc56-4b9b7176799c
    - SN_SERVICE_ADAPTER_CONFIG_FILE=service_adapter_config_example.yml
  working_dir: /agent
  command: python agent.py
  ports:
    - "8000:8000"
