
version: "3"

services:

    development:
      build: agent
      environment:
        - SN_AGENT_ID=b545478a-971a-48ec-bc56-4b9b7176799c
        - SN_NETWORK_WEB_PORT=8000
        - SN_SERVICE_ADAPTER_CONFIG_FILE=dev_config.yml
      ports:
        - "8000:8000"
      volumes:
        - ./data/agent/dev:/data
      links:
        - testrpc
        - relex

    testrpc:
      build: testrpc
      ports:
        - "8545:8545"
        - "8546:8546"
        - "30303:30303"
      command: testrpc

    relex:
      image: opencog/relex
      ports:
        - "9000:9000"
      command: bash -l -c ./link-grammar-server.sh 9000
