
version: "3"

services:

    alice:
      build: agent
      environment:
        - SN_AGENT_ID=b545478a-971a-48ec-bc56-4b9b7176799c
        - SN_AGENT_WEB_PORT=8000
        - SN_SERVICE_ADAPTER_CONFIG_FILE=service_adapter_config_example.yml
        - PYTHONPATH=/code
      ports:
        - "8000:8000"
      volumes:
        - ./agent-data:/data

    bob:
      build: agent
      environment:
        - SN_AGENT_ID=c545478a-971a-48ec-bc56-aaaaaaaaaaaa
        - SN_AGENT_WEB_PORT=8001
        - SN_SERVICE_ADAPTER_CONFIG_FILE=service_adapter_config_example.yml
        - PYTHONPATH=/code
      ports:
        - "8001:8001"
      volumes:
        - ./agent-data:/data

    agent-web:
      build: agent-web
      ports:
        - "8080:8080"
      environment:
        - SN_WEB_COOKIE_SECRET=kubr6DvIuYj4GREdgXq5CCoL5qHQWglj8IECTsI79mY=
        - PYTHONPATH=/code

    truffle:
      build: truffle
