
version: "3"

services:
    agent:
      build: agent
      environment:
        - SN_AGENT_ID=b545478a-971a-48ec-bc56-4b9b7176799c
        - SN_SERVICE_ADAPTER_CONFIG_FILE=service_adapter_config_example.yml
        - PYTHONPATH=/code
      ports:
        - "8000:8000"
      volumes:
        - ./agent-data:/data
      working_dir: /code
      entrypoint: ./run.sh
      command: noop

    agent-web:
      build: agent-web
      ports:
        - "8080:8080"
      environment:
        - SN_WEB_COOKIE_SECRET=kubr6DvIuYj4GREdgXq5CCoL5qHQWglj8IECTsI79mY=
      entrypoint: ./run.sh
      command: noop

#    geth:
#      build: geth
#      ports:
#        - "8545:8545"
#        - "8546:8546"
#        - "30303:30303"
#      volumes:
#        - ./geth-data:/geth-data
#      entrypoint: ./run.sh
#      command: noop
#      deploy:
#          resources:
#            limits:
#              cpus: '0.001'
#              memory: 50M
#            reservations:
#              cpus: '0.0001'
#              memory: 20M

#    parity:
#      build: parity
#      entrypoint: ./run.sh
#      command: noop
#
#    truffle:
#      build: truffle
#      entrypoint: ./run.sh
#      command: noop
