
version: "3"

services:

    agent:
      build: agent
      environment:
        - SN_AGENT_ID=b545478a-971a-48ec-bc56-4b9b7176799c
        - SN_SERVICE_ADAPTER_CONFIG_FILE=service_adapter_config_example.yml
        - PYTHONPATH=/code
      ports:
        - "8000:8000"
      volumes:
        - ./agent-data:/data

    agent-web:
      build: agent-web
      ports:
        - "8080:8080"
      environment:
        - SN_WEB_COOKIE_SECRET=kubr6DvIuYj4GREdgXq5CCoL5qHQWglj8IECTsI79mY=
        - PYTHONPATH=/code



    parity:
      build: parity
      volumes:
        - ./parity-data:/data

    ipfs:
      build: ipfs
      environment:
        - IPFS_PATH=/data
      volumes:
        - ./ipfs-data:/data
