
version: "3"

services:


    ipfs:
      build: ipfs
      environment:
        - IPFS_PATH=/data
      volumes:
        - ./data/ipfs:/data

    vault:
      build: vault
      hostname: vault
      ports:
        - "8200:8200"
      volumes:
        - ./data/vault-data/file:/vault/file
        - ./data/vault-data/config:/vault/config
        - ./data/vault-data/logs:/vault/logs
      cap_add:
        - IPC_LOCK

    geth:
      build: geth
      volumes:
        - ./data/geth-data:/geth-data
      ports:
        - "8080:8080"
        - "8180:8180"
        - "8545:8545"
        - "8546:8546"
        - "30303:30303"
        - "30303:30303/udp"
        - "30304:30304/udp"

    opendht:
      build: openDHT
      ports:
        - "4222:4222"
        - "9100:9100"
