
[Eth]
NetworkId = 3
SyncMode = "fast"

[Node]
DataDir = "/geth-data"
HTTPHost = "0.0.0.0"
HTTPModules = ["eth", "web3"]
WSModules = ["net", "web3", "eth", "shh"]


[Dashboard]
Host = "0.0.0.0"
Port = 8080
Refresh = 3000000000
